# Get token for AuthorizeCode [/nextgeniam/api/v1.0/oidc/token]
 
## Get token for AuthorizeCode [POST]
 

+ Request tokenRequest (application/json)
    + Headers
      Content-Type: application/json  
      Authorization: Basic MjY5YTI2YWNmYjQ1NDg2Mjg5OWNmOTJkZTMxY2JkOGQ6YzcwM3B6cTBVOENiUldKVVFZX1N6dTZwY1F3UDBOSGg4RWVvQ2Q1bFVUYT==
    + attributes (tokenRequest)
 
+ Response 200 (application/json)
    + Headers
      Content-Type: application/json      
    + attributes (tokenResponse)
