## getRolesMappedToApplicationResponse

+ roles: (array[getUserRolesResponse],fixed-type]) - The list of roles mapped to an application.
+ pagingInfo: (pagingInfo,object) - Paging related information.
