## GetUserRolesResponse
+ Name: 'RoleName' (string) - Role Name.
+ Description: 'RoleDescription' (string) - Description of role.
+ Status: 'Active/Inactive' (string) -Status of Role (Active/Inactive).
+ string Id: '1234567' (string) - Role Id.
+ CreatedAtUtc: '09-May-2022' (string) - Date on which role created.
+ UpdatedAtUtc: '09-May-2022' (string) - Date on which role was updated.
