## getUserRolesResponse
+ name: '01i052ghbke33/Readonly' (string) - Role name.
+ description: 'App role for read access : Application Developers and Support teams.' (string) - Role description.
+ status: 'Active' (string) - Status of role (Active/Inactive).
+ id: '01i062xarjqee' (string) - Role id.
+ createdAtUtc: '2022-03-24T10:18:37.52Z' (string) - Date on which role was created.
+ updatedAtUtc: '2022-03-24T10:18:37.52Z' (string) - Date on which role was updated.
