## tokenRequest

+ grant_type: 'clientcredentials' (string, required) - Provide grant type.
+ scope: 'openid' (string) - Provide the scope.
+ username: 'UserName' (string, optional) - Provide username.
+ password: '1234567' (string, optional) - Provide password.
+ code: 'Code' (string, optional) - Provide code.
+ redirect_uri: 'URL' (string) - Url to which need to be redirected on.
+ client_secret: 'ClientSecret' (string, optional) - Provide client secret.
+ client_id: 'ClientId' (string, optional) - Provide client id.
+ code_verifier: '4ttyyy567' (string, optional) - Provide code verifier as optional.
+ refresh_token: 'Bearer token' (string, optional) - Provide refresh token.
