## tokenResponse

+ access_token: 'eyJhbGciOiJSUzI1NiIspZCI6IjA5MzkwMkEwMDc4OEZGNDBDNEZCRTE3RTNBODVGRkIyMUIwQTYwNEMiLCJ0eXAiOiJKV1QifQeyJuYmYiOjE2NTMwNDkwMjIsImV4cCI6MTY1MzA1MjYyMiwiaWF0IjoxNjUzMDQ5MDIyLCJpc3MiOiJodHRwczovL25leH9wA' (string) - Access token to grant access to application.
+ token_type: 'Bearer' (string) - Type of token.
+ expires_in: 3600 (number) - Duration in seconds for which token is valid.
