## tokenRequest

+ grant_type: 'clientcredentials' (string, required) - Provide grant type.
+ scope: 'openid' (string) - Provide the scope.
+ username: 'UserName' (string, optional) - Provide username.
+ password: '1234567' (string, optional) - Provide password.
+ code: 'Code' (string, optional) - Provide code.
+ redirect_uri: 'URL' (string) - Url to which need to be redirected on.
+ client_secret: 'ClientSecret' (string, optional) - Provide client secret.
+ client_id: 'ClientId' (string, optional) - Provide client id.
+ code_verifier: '4ttyyy567' (string, optional) - Provide code verifier as optional.
+ refresh_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA5MzkwMkEwMDc4OEZGNDBDNEZCRTE3RTNBODVGRkIyMUIwQTYwNEMiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE2NTMwNDkwMjIsImV4cCI6MTY1MzA1MjYyMiwiaWF0IjoxNjUzMDQ5MDIyLCJpc3MiOiJodHRwczovL25leHRnZW4taWFtLnN0YWdlLmNueGxveWFsdHkuY29tIiwicm9sZXMiOltdLCJvd24iOiJPcmdhbml6YXRpb24iLCJpZCI6IjAxamYzN3Nmam5zcWMiLCJzdWIiOiIxYXAyYWc4Nmdhb2QiLCJzY29wZSI6Im9wZW5pZCBuYW1lIGVtYWlsIiwic293biI6IlVzZXIiLCJuYW1laWRlbnRpZmllciI6Im9yeGV1c2VySW50VGVzdDUyOTU5MjMzNDMzMjMiLCJmaXJzdE5hbWUiOiJkZW1vMSIsImxhc3ROYW1lIjoicGFydGljaXBhbnQiLCJlbWFpbCI6InBrQHRlc3QuY29tIiwiYXVkIjoiZDU4NTk2YTVhNzM3NDBiODk2OGIxZDBkNjY0MDE4ZmIifQ.uRMbex1p4piS3z1JAFkDSHYxqRRCcPF6yw0ebIwcIE1w5Zc5op9K4qRAZ_R7pAR2bROaNJ3uYpVYXqEZqwTNvNVVGSqqKIQfHyIYz39B4Kv098MCGVFnKDET" (string, optional) - Provide refresh token.
