## tokenRequest

+ `grant_type`: `client_credentials` (string) - It should be client_credentials.
+ scope: `open_id` (string) - The supported scopes are openid and context_app:<ApplicationId>.
+ redirect_uri: `https://nextgen-serviceauth.stage.cnxloyalty.com` (string) - URL to which request will be redirected.

