# Get Roles Mapped To Application [/nextgeniam/api/v1.0/applications/{applicationId}/clientRoles?pageNumber={pageNumber}&pageSize={pageSize}]
 
## Get Roles Mapped To Application [GET]
 
+ Parameters
    + applicationId: `01i052ghbkmwz` (string) - Application id of the application.   
    + pageNumber: 1 (number, optional) - Page number.
    + pageSize: 10 (number, optional) - Size of page.
   
 
+ Request getRolesMappedToApplicationReq (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationId: ab400bf5-7e20-481d-ae8a-be3ec12f0514
      cnx-tenantId: 2o9o3ae99ts
      Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjIxQ0Y2NUNFNUVFNUY1RjM1RTVCNTgzNkI2MDVBNTMyRjJCNDAwOTkiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE2NTMwNTEzOTIsImV4cCI6MTY1MzA1NDk5MiwiaWF0IjoxNjUzMDUxMzkyLCJpc3MiOiJodHRwczovL3ByaXZhdGUtbmV4dGdlbi1zZXJ2aWNlYXV0aC5xYS5jbnhsb3lhbHR5LmNvbSIsInRpZCI6IjJvOW8zYWU5OXRzIiwib3duIjoiQWNjb3VudCIsImlkIjoiMDFqZjQzaTEza2k2OSIsInN1YiI6IjI2OWEyNmFjZmI0NTQ4NjI4OTljZjkyZGUzMWNiZDhkIiwic2NvcGUiOiJvcGVuaWQiLCJzb3duIjoiQ2xpZW50IiwiYXVkIjoiMjY5YTI2YWNmYjQ1NDg2Mjg5OWNmOTJkZTMxY2JkOGQiLCJ0ZW5hbmN5QWNjZXNzIjoiQWxsIn0.odqJLIh9xRDukg6yG4Tc0jxx3TRLK0XGCfMmmu1zP0LwJGZrWVrb1daplnk2u7dAF3W0vFRGK5RcHdNHyJ2nHz0gw9Wxq-VkJHJuTXp8IDInXP-NsZx13Tr8I3NDd6PSM06tyVr7y4UvX7n-GDQmDVJySegnAgsP1eo9Dx8jU1FYN9QDFsMRr-8toAw3viM6loWg1nK3cBufLUlF-BChFbzH78gV1ZME5IXhTEF4i9pfWoYF1Y8kFDpBSfXnQjKZ3IuPQCNYs5aFZWftIKscXKqtf-r8JXcgDxLDvIFTaaVhK7Nx1HqJ3Hca4T5anUL7QUQnjiGh_jrK9n-n7OA5SA
   
 
+ Response 200 (application/json)
    + Headers
      Content-Type: application/json
      cnx-correlationId: ab400bf5-7e20-481d-ae8a-be3ec12f0514   
    + attributes (array [getRolesMappedToApplicationResponse], fixed-type)
